# Generated by Django 5.0.1 on 2024-01-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageDough', '0002_dough_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryraw',
            name='qty',
            field=models.FloatField(default=0),
        ),
    ]
